### ISSUE TITLE
I think your age descriptions are mixed up

### ISSUE THREAD

**Issue by brisingraerowing** [Orange1861/Improved-Villagers#14]
![2017-06-24_10 44 05](https://user-images.githubusercontent.com/250409/27509403-254b05d8-58ca-11e7-8c1c-15f73d8243a8.png)
![2017-06-24_10 44 08](https://user-images.githubusercontent.com/250409/27509404-26a26764-58ca-11e7-9f6a-9da735e4bdc8.png)

Yeah, I don't think that little guy is an Elder.

The others are mixed up as well.

**Comment by Orange1861** [comment]
Does this happen to all villagers or just children villagers?

**Comment by brisingraerowing** [comment]
I'm not sure about the other villagers, but they do seem to be a bit off (like a white haired villager showing as middle aged).

Sadly, this mod doesn't work all that well with some other mods I have, so I ended up removing it.

Still, it's a great mod.

**Comment by Orange1861** [comment]
What issues does this mod have with other mods, this mod is relatively new, and I still need to patch up compatibility.

**Comment by Orange1861** [comment]
The above issue has bee fixed in 2.1.2.

**Comment by brisingraerowing** [comment]
The main issue is that custom village structures don't spawn (like any from Recurrent Complex or Immersive Engineering).

**Comment by Orange1861** [comment]
Yeah, this is a known issue, hopefully a fix will be out eventually but this is a difficult issue to fix.
