### ISSUE TITLE
Empty Plat, Again

### ISSUE THREAD

**Issue by mgwerner** [Orange1861/Improved-Villagers#15]
Forge 13.20.0.2300

Have started yet another new world, found this after 20-25 villages.  Photo won't attach, but like the other issue I posted last week, pathways and cleared areas with plank floors are present, but no structures or villagers.

**Comment by Orange1861** [comment]
Hmmm, well this seems to be a rare issue. Post your console logs, disable cities in the config and post your mod list. If this still happens after disabling cities then this is a major issue, since that would mean that this is a core issue. If cities is the issue, then I'll modify them to be less buggy.

**Comment by mgwerner** [comment]
I think these are the logs you want.  Screenshot of my mod folder.  Screenshot of the village.  Chinese internet is crap, so let me know if they did not upload properly.  Thanks!

[2017-06-25-5.log.gz](https://github.com/Orange1861/Improved-Villagers/files/1100286/2017-06-25-5.log.gz)


![image](https://user-images.githubusercontent.com/12369588/27515939-82863bce-59e1-11e7-9bb9-468c72a41b7e.png)
![2017-06-25_18 25 39](https://user-images.githubusercontent.com/12369588/27515940-8d61f4f2-59e1-11e7-9ce6-591c785d37d0.png)

**Comment by Orange1861** [comment]
This is an issue with this mod thank you. I will be looking for a solution in the next few days.

**Comment by mgwerner** [comment]
Cool, glad to help.  I enjoy the mod a lot with the massive villages.

**Comment by mgwerner** [comment]
Still happening, this time the village looks too small, which is why I was sending it in even though you are working the issue:

![2017-06-27_13 59 36](https://user-images.githubusercontent.com/12369588/27572873-20a4e9bc-5b41-11e7-8cc5-48b9ab1db987.png)
![2017-06-27_13 59 17](https://user-images.githubusercontent.com/12369588/27572874-20a685a6-5b41-11e7-9d00-c102bf4f92a9.png)
