### ISSUE TITLE
Immersive Engineering Integration

### ISSUE THREAD

**Issue by mgwerner** [Orange1861/Improved-Villagers#16]
I am not sure about this one, since you have my logs and such, I thought I would drop it in here.

None of the villages in my world have an IE house and villager.  Perhaps a villager would appear, there are a lot of them, but there is no house in the 12-15 villages I have visited. 

Is this an integration issue?  Does it only affect the structure, or will the villager not appear?  They are needed for some trades mid-game.

Cheers

**Comment by Orange1861** [comment]
This is an known issue with the village generation. Non-vanilla structures will not spawn in this mod's villages, this is a known issue. This mod does not override villagers from other mods but this mod recently changed from spawning vanilla villagers and overriding them to actually spawning this mod's villagers which is an issue. 

Basically, other mod's villagers do not spawn in the villages, BUT they will spawn in every other case. In the future, I will aim to fix this but there are many solutions to this problem for the current version.
1. Find and cure a zombie villager, it may become the villager you are looking for. - Note zombie villagers are mostly un-tested so I'm not sure if this will work.
2. Disable override villagers and go to a new village, when override villagers is disabled it, this mod's villages will spawn vanilla villagers with the old way. After finding the villager you are looking for reenable the override villagers and the override will convert all vanilla villagers into this mod's villagers again.
3. Get villager spawn eggs and start spawning villagers, you should eventually get a villager that you want. Override villagers has no impact on this.
4. Use commands to spawn a villager and keep doing it, you should eventually get a villager that you want. Override villagers has no impact on this.

These are many of the solutions that come to mind, tell me if you need other ones.

**Comment by Orange1861** [comment]
Actually, this will be fixed in 2.1.2 so you won't have to wait long 👍.

**Comment by mgwerner** [comment]
Thanks for that.

If I create my own "village," by capturing a couple of villagers and putting them in a fenced area with doors, the IE villager will eventually spawn?  This is my usual method of having villagers for trading at my base.  It is mid-game, so will solve the issue for me.  Loot from the IE structure will be missing, but that;s fine with me.

**Comment by mgwerner** [comment]
Nice one.  I'll limit my exploration of the new world until the update.  Thanks again for your patience.

**Comment by Orange1861** [comment]
Thank you for your patience to use this mod and not giving up on this mod with its numerous small issues. The change to the mod is basically the small houses will generate two vanilla villagers and if the profession is from vanilla then they will be overridden, otherwise they remain as villagers from the mod they are from.

**Comment by Orange1861** [comment]
Also, the update is out! It was going to be bigger patch but I was at a stopping point where I could release it.

**Comment by mgwerner** [comment]
WOW!  Thanks for that.

I don't mind working with things in development, as it gives me more things to fiddle with and discover.  I'm semi-retired, so have the time.....

Cheers!

**Comment by mgwerner** [comment]
Well, I cannot see how the update fixed this.  I have been troubleshooting TechReborn, looking for rubber tree saplings, so have created several Creative worlds, and flown around looking for them.  No IE structures in any of the dozen or so villages I have seen.

That being said, this was pretty:

![2017-06-26_22 20 02](https://user-images.githubusercontent.com/12369588/27543839-f858b4d0-5abd-11e7-887d-4422ec37a8b3.png)

**Comment by Orange1861** [comment]
I didn't fix the structures, I only was able to allow villagers from other mods to spawn in the small houses.

**Comment by mgwerner** [comment]
Ah, I misunderstood then.  Thanks for the clarification.  I was not paying attention to the types of villagers, I will do so now.

**Comment by Orange1861** [comment]
@mgwerner Please tell me if you can't find any or any other smaller suggestions to villages. But yeah, that is a beautiful village.

**Comment by mgwerner** [comment]
Hmmm, deleted the regions to have Recurrent Complex structures respawn.  Now I have no villages at all.  Using 2.1.2.

**Comment by Orange1861** [comment]
Idk why that is happening, can you give me more info?

**Comment by mgwerner** [comment]
What else would you like to know?

Recurrent Complex did an update, which required deleting the regions and its .dat file in order to correct some rendering issues.  That was fixed, and I expected villages to have to respawn, but they never did.  I suspect this is a RC issue, and will post on that github.  I also added Dooglamoo Cities, but deleted it and the regions, suspecting that was the issue.  Apparently not, as I cannot find a village in the re-rendered regions after deleting DC.

**Comment by Orange1861** [comment]
Hmm, does removing this mod cause villages to spawn (in a different place)?

**Comment by mgwerner** [comment]
Yes, it does.  Took a while to delete/load, etc., Dooglamoo is not the culprit, Recurrent Complex seems to be.  Both yours and RC worked well together befoer the last update for both.  Not sure what is conflicting, but there is a setting in RC to not spawn structures within a certain distance.  Maybe that is too large, so nothing else is spawning.
