### ISSUE TITLE
Linux Dedicated server error, & can't access Villager by right-click

### ISSUE THREAD

**Issue by drakray** [Orange1861/Improved-Villagers#17]
Error in server log, a LOT of them https://pastebin.com/d0FzhwYh (more then 5000 over night)

**Comment by drakray** [comment]
[modList](https://pastebin.com/jN4Jrzqd)

**Comment by Orange1861** [comment]
This is a severe issue, however, I require more info. Which version are you using and show me more of the crash log, the information below the Java:NullpointerException is where usually I get the info.

**Comment by drakray** [comment]
Full log:
[fml-server-1.log.txt](https://github.com/Orange1861/Improved-Villagers/files/1154814/fml-server-1.log.txt)

MC 1.11.2
Forge 2414
Improved Villager 2.1.2

**Comment by drakray** [comment]
There is no crashlog, just the error in the log, until I closed the server and restart with
B:"Override Original Villagers?"=false
B:"Revert Back to Original Villagers"=true
which patch the issue to make my server playable

**Comment by Orange1861** [comment]
Fixed in 3.0.1.
