### ISSUE TITLE
IV-2.1.4 Villager blinking(or jumping)

### ISSUE THREAD

**Issue by MadRatSRP** [Orange1861/Improved-Villagers#25]
When u use The One Probe and move your cursor on the villager, little model left from the his name and mod's name will jump or blink, like it tries to become bigger xD

**Comment by Orange1861** [comment]
I'm sorry, I do not understand the issue, What is the "One Probe"? Do you mean the notification marker?

**Comment by MadRatSRP** [comment]
The One Probe is a minecraft mod that works like Waila in previous versions of minecraft https://minecraft.curseforge.com/projects/the-one-probe?gameCategorySlug=mc-mods&projectID=245211

![blinking](https://user-images.githubusercontent.com/29717217/29632211-f4b7545c-884a-11e7-8967-04d3a925da81.png)
u see small model of villager in the top left corner? its the one probe interface. That small model is blinking or jumping, its not static, its not just an image, it is like a villager, whos head is trying to jump from the body))

**Comment by Orange1861** [comment]
Oh, so the issue is that the model is trying to become an actual villager and stuff?

**Comment by MadRatSRP** [comment]
Not the whole model, but only the head of it, its shaking.

**Comment by Orange1861** [comment]
I do not know, ask the One Probe devs or something.
