### ISSUE TITLE
Empty Village Plat

### ISSUE THREAD

**Issue by mgwerner** [Orange1861/Improved-Villagers#7]
Minimap shows outlines of building placement, with pathways, but there are not any buildings on the landscape, and only the pathways between where they should be.  No villagers.  This is occurring in a new world, with Beta 3.

not occurring in Beta 2, same world seed, village in place where outline was in Beta 3,
![2017-06-15_18 26 11](https://user-images.githubusercontent.com/12369588/27177973-eb5b79dc-51fa-11e7-96aa-d6eae42e26b2.png)

**Comment by Orange1861** [comment]
Does this happen with all worlds or just this one? If you try to generate the world a second time, does this happen? I'll definitely look into this.

Thanks for posting here!

**Comment by mgwerner** [comment]
I could not recreate this.

I tried a new world, same seed, with Beta 3, ran around and found five villages all as they should be.

The only thing I can figure is that when I got your mod and added it to my world, the current villages were devoid of villagers.  New villages were fine, the others were all empty.  Not killed off, as I started that world the day before, not enough time, only day 3.  So I started a new world, with the same seed, and the same name, but I deleted the old game from the client.

Deleted the old worlds, started again, same seed, Beta 3, completely different world name, no issues.  All villages I had investigated are there.

Could there have been an artifact in the game that associated the old save with the new world?  I assume I can avoid that by not using the same world name.   I assume it had something to do with the names of the worlds being the same.  I know little about mods, but it seems logical to me.

Interesting mod, thanks for developing it.  Glad to be of help, even if it appears to be a rare issue.

Cheers!

**Comment by Orange1861** [comment]
Well, there is a 1/20 chance of a village spawning as a massive village which could be bugged and break villages 1/20th of a time. Names of worlds rarely cause issues, but I always name worlds differently just in case. Thank you for using this github, I need people to use this more.

**Comment by Orange1861** [comment]
I'll close this issue until it can be reproduced.

**Comment by mgwerner** [comment]
I'll keep exploring the new world over the weekend, and let you know if I experience anything else untoward.

Thanks for the swift responses.
