### ISSUE TITLE
[1.10.2] [LATEST VERSION] Right clicking a villager caused me to crash?

### ISSUE THREAD

**Issue by ImadethisjustforNVIDIAFleX** [Orange1861/Improved-Villagers#9]
I have other mods on but the exact moment I right clicked on a villager, my game crashed. It was one of the named villagers from this mod so I think this mod is what caused it, help/fix please?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IvToolkit (IvToolkit-1.3.3-1.10.jar)
  SCFMLCorePlugin (StalkerCreepers-1.10.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 6/19/17 5:53 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at orangeVillager61.ImprovedVillagers.Entities.IvVillager.func_184645_a(IvVillager.java:877)
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1229)
	at net.minecraft.entity.player.EntityPlayer.func_184822_a(EntityPlayer.java:1161)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:535)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1506)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at orangeVillager61.ImprovedVillagers.Entities.IvVillager.func_184645_a(IvVillager.java:877)
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1229)
	at net.minecraft.entity.player.EntityPlayer.func_184822_a(EntityPlayer.java:1161)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:535)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1506)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['34ivan43'/2405, l='MpServer', x=128.97, y=64.02, z=261.70]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (124,64,256), Chunk: (at 12,4,0 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2163 game time, 2163 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 128 total; [EntityItem['item.tile.sand.default'/3328, l='MpServer', x=140.86, y=62.00, z=258.02], EntityItem['item.tile.sand.default'/3330, l='MpServer', x=141.34, y=61.00, z=259.40], EntityZombie['Zombie'/2564, l='MpServer', x=150.70, y=33.04, z=292.30], EntityItem['item.tile.sand.default'/3332, l='MpServer', x=142.69, y=62.00, z=257.41], EntityItem['item.tile.sand.default'/3333, l='MpServer', x=140.13, y=61.00, z=257.16], EntityItem['item.tile.sand.default'/3334, l='MpServer', x=141.88, y=62.00, z=256.13], EntityItem['item.tile.sand.default'/3335, l='MpServer', x=140.67, y=63.00, z=256.13], EntityItem['item.tile.sand.default'/3337, l='MpServer', x=141.66, y=63.00, z=261.47], EntityItem['item.tile.sand.default'/3338, l='MpServer', x=142.88, y=63.00, z=261.88], EntitySkeleton['Skeleton'/2575, l='MpServer', x=111.50, y=21.00, z=298.50], EntityItem['item.tile.dirt.default'/2832, l='MpServer', x=125.13, y=65.00, z=262.88], EntityItem['item.tile.dirt.default'/2833, l='MpServer', x=128.42, y=57.00, z=262.13], EntityCreeper['Creeper'/2579, l='MpServer', x=143.43, y=62.00, z=260.70], EntityItem['item.tile.sand.default'/2835, l='MpServer', x=129.31, y=64.00, z=266.88], EntityCreeper['Creeper'/2584, l='MpServer', x=130.24, y=64.00, z=263.32], EntityItem['item.tile.dirt.default'/2844, l='MpServer', x=130.88, y=64.00, z=264.88], EntityPig['Pig'/3358, l='MpServer', x=199.50, y=64.00, z=279.50], EntityItem['item.tile.dirt.default'/2591, l='MpServer', x=125.13, y=65.00, z=263.88], EntityPig['Pig'/3359, l='MpServer', x=200.50, y=64.00, z=278.50], EntityCow['Cow'/3360, l='MpServer', x=198.50, y=64.00, z=278.50], EntityItem['item.item.seeds'/2593, l='MpServer', x=125.13, y=65.00, z=258.95], EntityItem['item.tile.dirt.default'/2596, l='MpServer', x=125.13, y=65.00, z=258.13], EntityItem['item.tile.dirt.default'/2600, l='MpServer', x=125.13, y=65.00, z=258.95], EntityScent['entity.zombieawareness.EntityScent.name'/3368, l='MpServer', x=131.57, y=65.00, z=263.07], EntityItem['item.tile.sand.default'/3369, l='MpServer', x=133.88, y=62.00, z=260.30], EntityItem['item.tile.dirt.default'/3373, l='MpServer', x=136.88, y=61.00, z=260.60], EntityItem['item.tile.sandStone.default'/3375, l='MpServer', x=129.90, y=64.00, z=266.27], EntityItem['item.tile.sand.default'/3376, l='MpServer', x=132.14, y=65.00, z=265.67], EntityItem['item.tile.sand.default'/3377, l='MpServer', x=133.59, y=65.00, z=264.97], EntityItem['item.tile.stonebrick'/3378, l='MpServer', x=132.88, y=63.00, z=263.88], EntityItem['item.tile.sandStone.default'/3379, l='MpServer', x=131.23, y=57.00, z=261.50], EntityItem['item.tile.sand.default'/3381, l='MpServer', x=133.88, y=63.00, z=262.80], EntityItem['item.tile.sand.default'/3382, l='MpServer', x=132.88, y=57.00, z=262.88], EntityItem['item.tile.sand.default'/3383, l='MpServer', x=135.54, y=65.00, z=263.13], EntityCreeper['Creeper'/2626, l='MpServer', x=132.11, y=57.88, z=261.30], EntityCreeper['Creeper'/2629, l='MpServer', x=125.51, y=65.00, z=258.99], EntityItem['item.tile.sand.default'/3398, l='MpServer', x=134.88, y=65.00, z=262.27], EntityCreeper['Creeper'/2631, l='MpServer', x=132.27, y=63.00, z=260.71], EntityItem['item.tile.stonebrick'/3399, l='MpServer', x=132.88, y=57.00, z=262.88], EntityCreeper['Creeper'/2633, l='MpServer', x=139.93, y=62.00, z=258.50], EntityCreeper['Creeper'/2381, l='MpServer', x=144.50, y=34.00, z=332.50], EntityScent['entity.zombieawareness.EntityScent.name'/3407, l='MpServer', x=127.65, y=65.00, z=260.30], EntityItem['item.tile.dirt.default'/3408, l='MpServer', x=127.06, y=64.00, z=260.99], EntityItem['item.tile.stonebrick'/3412, l='MpServer', x=127.13, y=63.00, z=261.31], EntityItem['item.tile.dirt.default'/2645, l='MpServer', x=129.20, y=63.00, z=259.13], EntityZombie['Zombie'/2391, l='MpServer', x=171.42, y=19.00, z=259.70], EntityItem['item.tile.sand.default'/3415, l='MpServer', x=124.48, y=67.00, z=260.71], EntityBat['Bat'/2393, l='MpServer', x=181.93, y=18.11, z=286.66], EntityItem['item.tile.dirt.default'/3417, l='MpServer', x=126.22, y=64.00, z=259.64], EntityItem['item.tile.dirt.default'/3419, l='MpServer', x=129.46, y=64.00, z=258.00], EntityItem['item.tile.sand.default'/2652, l='MpServer', x=101.42, y=42.00, z=283.88], EntityItem['item.tile.dirt.default'/3420, l='MpServer', x=128.37, y=63.00, z=259.16], EntityItem['item.tile.dirt.default'/3421, l='MpServer', x=130.88, y=64.00, z=258.39], EntityItem['item.tile.dirt.default'/3422, l='MpServer', x=126.28, y=65.00, z=258.32], EntitySkeleton['Skeleton'/2398, l='MpServer', x=204.50, y=18.00, z=225.50], EntityItem['item.tile.dirt.default'/3423, l='MpServer', x=129.13, y=64.00, z=257.13], EntityItem['item.tile.dirt.default'/3424, l='MpServer', x=127.53, y=64.00, z=257.13], EntityItem['item.tile.sand.default'/3426, l='MpServer', x=127.12, y=65.00, z=264.88], EntityPlayerSP['34ivan43'/2405, l='MpServer', x=128.97, y=64.02, z=261.70], EntityCreeper['Creeper'/2678, l='MpServer', x=130.48, y=64.00, z=260.47], EntityCreeper['Creeper'/2680, l='MpServer', x=132.30, y=62.00, z=260.08], EntityBat['Bat'/3451, l='MpServer', x=170.42, y=17.10, z=321.98], EntityCreeper['Creeper'/2686, l='MpServer', x=127.30, y=63.00, z=261.70], EntityCreeper['Creeper'/3199, l='MpServer', x=132.76, y=58.24, z=261.30], EntityCreeper['Creeper'/2688, l='MpServer', x=140.85, y=61.00, z=257.45], EntityCreeper['Creeper'/3201, l='MpServer', x=135.62, y=64.17, z=259.07], EntityCreeper['Creeper'/2690, l='MpServer', x=134.52, y=62.00, z=260.00], EntityCreeper['Creeper'/3203, l='MpServer', x=125.52, y=65.00, z=258.33], EntityCreeper['Creeper'/2692, l='MpServer', x=129.30, y=58.30, z=261.88], EntityBat['Bat'/3464, l='MpServer', x=153.39, y=23.03, z=319.50], EntityBat['Bat'/3465, l='MpServer', x=138.49, y=26.46, z=326.57], EntityBat['Bat'/3466, l='MpServer', x=139.61, y=27.03, z=332.70], EntityCreeper['Creeper'/2702, l='MpServer', x=125.21, y=65.08, z=246.49], IvVillager['Howard'/3476, l='MpServer', x=132.85, y=62.00, z=259.30], EntityCreeper['Creeper'/2709, l='MpServer', x=131.19, y=58.65, z=261.70], EntityCreeper['Creeper'/3222, l='MpServer', x=128.31, y=63.00, z=259.89], EntityCreeper['Creeper'/3224, l='MpServer', x=135.27, y=62.95, z=260.33], IvVillager['Donald'/3480, l='MpServer', x=131.50, y=65.00, z=259.50], EntityCreeper['Creeper'/3226, l='MpServer', x=131.77, y=58.43, z=262.49], IvVillager['Anglica'/3484, l='MpServer', x=129.52, y=63.00, z=260.14], EntityItem['item.tile.sand.default'/2718, l='MpServer', x=137.38, y=62.00, z=254.15], EntityCreeper['Creeper'/3230, l='MpServer', x=140.73, y=62.00, z=258.22], EntityItem['item.tile.sand.default'/2719, l='MpServer', x=128.17, y=68.00, z=267.88], EntityCreeper['Creeper'/3232, l='MpServer', x=134.52, y=65.00, z=264.66], IvVillager['Anna'/3488, l='MpServer', x=127.30, y=63.00, z=259.56], EntityItem['item.tile.sand.default'/2722, l='MpServer', x=131.10, y=66.00, z=267.88], EntityCreeper['Creeper'/3234, l='MpServer', x=130.70, y=65.00, z=259.71], EntityCreeper['Creeper'/3236, l='MpServer', x=131.63, y=62.00, z=262.44], IvVillager['Otto'/3493, l='MpServer', x=126.50, y=64.00, z=260.50], EntityCreeper['Creeper'/3239, l='MpServer', x=130.45, y=63.00, z=261.74], EntitySkeleton['Skeleton'/2472, l='MpServer', x=162.50, y=30.00, z=291.79], EntityBat['Bat'/3496, l='MpServer', x=200.25, y=16.00, z=320.75], EntityBat['Bat'/3497, l='MpServer', x=199.25, y=16.03, z=319.75], EntityItem['item.tile.sand.default'/2730, l='MpServer', x=131.88, y=62.00, z=262.25], EntityCreeper['Creeper'/3244, l='MpServer', x=133.51, y=62.00, z=260.68], EntityBat['Bat'/3256, l='MpServer', x=150.30, y=24.66, z=313.32], EntityCreeper['Creeper'/3259, l='MpServer', x=132.30, y=62.00, z=259.49], EntitySkeleton['Skeleton'/2499, l='MpServer', x=90.60, y=35.00, z=287.82], EntityBat['Bat'/3269, l='MpServer', x=170.60, y=18.87, z=327.55], EntityItem['item.tile.sand.default'/2759, l='MpServer', x=133.88, y=66.00, z=267.88], EntityCreeper['Creeper'/3273, l='MpServer', x=139.72, y=62.00, z=259.44], EntityItem['item.tile.sand.default'/2762, l='MpServer', x=135.88, y=66.00, z=266.88], EntityCreeper['Creeper'/3275, l='MpServer', x=132.80, y=58.61, z=263.47], EntityCreeper['Creeper'/3277, l='MpServer', x=143.10, y=62.00, z=257.49], EntityItem['item.tile.dirt.default'/2768, l='MpServer', x=132.88, y=63.00, z=263.88], EntityCreeper['Creeper'/3281, l='MpServer', x=140.23, y=64.18, z=261.49], EntityItem['item.item.rottenFlesh'/3283, l='MpServer', x=149.13, y=31.00, z=290.77], EntityItem['item.tile.sand.default'/2772, l='MpServer', x=135.88, y=65.00, z=264.88], EntityCreeper['Creeper'/3285, l='MpServer', x=140.78, y=64.00, z=253.60], EntityCreeper['Creeper'/3288, l='MpServer', x=141.88, y=61.00, z=258.40], EntityCreeper['Creeper'/3294, l='MpServer', x=136.26, y=63.00, z=259.74], EntityCreeper['Creeper'/2528, l='MpServer', x=178.50, y=24.00, z=281.50], EntityCreeper['Creeper'/3296, l='MpServer', x=130.82, y=64.00, z=263.59], EntityCreeper['Creeper'/3298, l='MpServer', x=133.42, y=62.00, z=259.43], EntityCreeper['Creeper'/3300, l='MpServer', x=127.93, y=63.00, z=261.15], EntityCreeper['Creeper'/3303, l='MpServer', x=129.49, y=64.00, z=262.08], EntityCreeper['Creeper'/3306, l='MpServer', x=137.33, y=62.00, z=256.51], EntityCreeper['Creeper'/3308, l='MpServer', x=132.90, y=62.00, z=260.09], EntityCreeper['Creeper'/3310, l='MpServer', x=132.99, y=62.00, z=260.70], EntityBat['Bat'/3055, l='MpServer', x=141.34, y=34.10, z=263.66], EntityCreeper['Creeper'/3312, l='MpServer', x=139.63, y=64.00, z=256.74], EntityCreeper['Creeper'/3314, l='MpServer', x=132.30, y=62.00, z=260.12], EntityCreeper['Creeper'/3317, l='MpServer', x=132.86, y=63.00, z=261.34], EntityScent['entity.zombieawareness.EntityScent.name'/3320, l='MpServer', x=141.76, y=64.00, z=258.92], EntityItem['item.tile.sand.default'/3322, l='MpServer', x=143.88, y=62.00, z=260.88], EntityItem['item.tile.sand.default'/3323, l='MpServer', x=140.32, y=61.00, z=259.30], EntityItem['item.tile.sand.default'/3324, l='MpServer', x=139.13, y=62.00, z=259.88], EntityItem['item.tile.sand.default'/3326, l='MpServer', x=139.73, y=62.00, z=258.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 258504656 bytes (246 MB) / 759148544 bytes (723 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 34, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAAAAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281.jar) 
	UCHIJAAAAAAAAA	ivtoolkit{1.3.3-1.10} [IvToolkit] (minecraft.jar) 
	UCHIJAAAAAAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAAAAAAA	chameleoncreepers{1.4.1} [Chameleon Creepers] (chameleoncreepers-1.4.1-1.10.2.jar) 
	UCHIJAAAAAAAAA	extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.16.jar) 
	UCHIJAAAAAAAAA	coroutil{1.10.2-1.1.16} [CoroUtil Library] (coroutil-1.10.2-1.1.16.jar) 
	UCHIJAAAAAAAAA	configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.16.jar) 
	UCHIJAAAAAAAAA	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCHIJAAAAAAAAA	creeperawareness{2.0.2} [Creeper Awareness] (CreeperAwareness-2.0.2-1.10.2.jar) 
	UCHIJAAAAAAAAA	iv{1.1.0 - Beta 1} [Improved Villagers] (iv-1.1.0 - Beta 1.jar) 
	UCHIJAAAAAAAAA	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCHIJAAAAAAAAA	openglider{@VERSION@} [Open Glider] (OpenGlider-1.10.2-1.0.0.jar) 
	UCHIJAAAAAAAAA	reccomplex{1.3.2-1.10} [Recurrent Complex] (RecurrentComplex-1.4-1.10 (1).jar) 
	UCHIJAAAAAAAAA	special_ai{1.1.3} [Special AI] (special_ai-1.10.2-1.1.3.jar) 
	UCHIJAAAAAAAAA	zombieawareness{1.10.2-1.11.7} [Zombie Awareness] (zombieawareness-1.10.2-1.11.7.jar) 
	Loaded coremods (and transformers): 
IvToolkit (IvToolkit-1.3.3-1.10.jar)
  
SCFMLCorePlugin (StalkerCreepers-1.10.2.jar)
  atomicstryker.stalkercreepers.common.SCTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.50' Renderer: 'GeForce GT 630/PCIe/SSE2'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2281
	LWJGL: 2.9.4
	OpenGL: GeForce GT 630/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.50, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.11.2-rv4.zip, [32x32]Vaders Alternative Faithful Pack V1.2 For MC 1.11.zip, Faithful Mods 1.11.2-rv4.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz

**Comment by Orange1861** [comment]
This is definitely an issue with Improved Villagers, I'll check it tomorrow. A fix will probably be done tomorrow.

Thanks for posting on github!

**Comment by Orange1861** [comment]
Fixed this in beta 2.
